name: zk_finger
description: The zk_finger plugin is used for supporting fingerprint device of zkecto with enrolling and verification feature.
version: 2.0.0
homepage: https://github.com/amorenew/flutter_zkteco_fingerprint.git

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.zkteco.zkfinger
    pluginClass: ZkFingerPlugin